$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: model
command: >-
  python train.py
  --training_data ${{inputs.training_data}}
  --reg_rate ${{inputs.reg_rate}}
inputs:
  training_data: 
    type: uri_folder 
    path: azureml:diabetes-prod-folder:1
  reg_rate: 0.01
environment: azureml://registries/azureml/environments/sklearn-1.1/versions/34
compute: mslearn-mlops-compute-cluster
experiment_name: mslearn-mlops-prod-exp
description: This is for mslearn mlops training in prod env
