name: Manually trigger an Azure Machine Learning job

on:
  push:
    branches:
      - main

jobs:
  trainindev:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job.yml -w mslearn-mlops -g SdmRG
  traininprod:
    needs: trainindev
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/prod_job.yml -w mslearn-mlops -g SdmRG
  register_and_deploy:
    environment: Production
    runs-on: ubuntu-latest
    needs: traininprod
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Register Model and Deploy Endpoint
      run: |
        export ENDPOINT_NAME="mslearn-mlops-endpoint"
        az ml model create --name mslearn-mlops --type "mlflow_model" --path "${{ secrets.MODEL_URI }}" --workspace-name mslearn-mlops --resource-group SdmRG          
          
