name: Manually trigger an Azure Machine Learning job

on: [pull_request]

jobs:
 job1:
    name: linting
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install Flake8
      run: |
        python -m pip install flake8
    - name: Run linting tests
      run: | 
        flake8 src/model/
 job2:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
    - name: install pytest
      run: |
        pip install -r ../requirements.txt
    - name: run unit tests
      run: | 
        pytest tests/


